# -*- coding: utf-8 -*-
"""scratchpad

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/empty.ipynb
"""

import numpy as np
import matplotlib.pyplot as plt

# Yurak shaklini parametrik tenglamalari
t = np.linspace(0, 2 * np.pi, 1000)
x = 16 * np.sin(t)**3
y = 13 * np.cos(t) - 5 * np.cos(2 * t) - 2 * np.cos(3 * t) - np.cos(4 * t)

# Grafikni chizish
plt.figure(figsize=(6,6))
plt.plot(x, y, color='red')
plt.fill(x, y, color='red', alpha=0.6)  # Yurak shaklini to'ldirish
plt.title('Yurak shakli')
plt.axis('off')  # O'qlarni ko'rsatmaslik
plt.show()